version: '3.9'

services:
  server:
    build:
      context: ./server
    environment:
      - PORT=5000
    ports:
      - '5000:5000'

  client:
    build:
      context: ./client
    environment:
      - VITE_API_BASE_URL=http://server:5000/api
      - VITE_API_PROXY_TARGET=http://server:5000
    ports:
      - '5173:5173'
    depends_on:
      - server
